import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar"; // Correctly import the NavBar component

export const metadata: Metadata = {
  title: "SnapZoska",
  description: "Generated by me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sk">
      <body>
        <div style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>
          <main style={{ flex: 1 }}>{children}</main> {/* Content area */}
          <footer>
            <NavBar /> {/* Bottom navigation */}
          </footer>
        </div>
      </body>
    </html>
  );
}
